name: smoke-test
on:
  push:
  workflow_dispatch:

jobs:
  hello:
    runs-on: docker
    steps:
      - name: Hostname & OS
        run: |
          echo "Running on: $(hostname)"
          cat /etc/os-release
      - name: Node check
        run: node --version
      - name: Network check
        run: |
          curl -sS https://codeberg.org/api/v1/version
